drop table if exists churn_labels;
CREATE TABLE churn_labels (
    customer_id VARCHAR(100) PRIMARY KEY,
    signup_date DATE,
    age INT,
    gender VARCHAR(10),
    annual_income VARCHAR(20),
    education VARCHAR(50),
    marital_status VARCHAR(30),
    dependents VARCHAR(20),
    tenure INT,
    contract VARCHAR(50),
    payment_method VARCHAR(50),
    paperless_billing VARCHAR(10),
    senior_citizen VARCHAR(10),
    monthlycharges VARCHAR(20),
    totalcharges VARCHAR(20),
    num_services INT,
    has_phone_service VARCHAR(10),
    has_internet_service VARCHAR(10),
    has_online_security VARCHAR(10),
    has_online_backup VARCHAR(10),
    has_device_protection VARCHAR(10),
    has_tech_support VARCHAR(10),
    has_streaming_tv VARCHAR(10),
    has_streaming_movies VARCHAR(10),
    customer_satisfaction VARCHAR(20),
    num_complaints VARCHAR(20),
    num_service_calls VARCHAR(20),
    late_payments VARCHAR(20),
    avg_monthly_gb VARCHAR(20),
    days_since_last_interaction VARCHAR(20),
    credit_score VARCHAR(20),
    churn TINYINT NOT NULL
);